debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"

[api]
dashboard = true
entryPoint = "traefik"

[file]
watch = true

[frontends]
  [frontends.octoprint]
  backend = "b_octoprint"
    [frontends.octoprint.routes.r1]
    rule = "Host: octoprint.ranii.pro"
  [frontends.transmission]
  backend = "b_transmission"
    [frontends.transmission.routes.r1]
    rule = "Host: transmission.ranii.pro"

[backends]
  [backends.b_octoprint]
    [backends.b_octoprint.servers.raspi]
    url = "http://alarmpi:5000"
    weight = 1
  [backends.b_transmission]
    [backends.b_transmission.servers.server]
    url = "http://rani-server:9091"
    weight = 1

[docker]

