version: '3.6'

services:
  traefik:
    image: traefik:v1.7.0-rc3-alpine 
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTP port
      - "8080:8080" # The Web UI 
    labels:
      - "traefik.frontend.rule=Host:monitor.ranii.pro"
      - "traefik.port=8080"
    restart: always
    environment:
      - LEXICON_SLEEP_TIME=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Doc
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /opt/traefik/rules.toml:/etc/traefik/rules.toml
      - /opt/traefik/acme/acme.json:/etc/traefik/acme/acme.json
    container_name: traefik
 
  h5ai:
    image: corfr/h5ai
    restart: always
    labels:
      - "traefik.frontend.rule=Host:download.ranii.pro"
    volumes:
      - /mnt/NAS/http:/var/www

  h5ai_internal:
    image: corfr/h5ai
    restart: always
    labels:
      - "traefik.frontend.rule=Host:internal.ranii.pro"
      - "traefik.frontend.auth.basic=user:$$apr1$$lAIgLetv$$5HpJQ0tkjwqHgUeeT5tGx1"
    volumes:
      - /mnt/NAS/http_internal:/var/www
  
  whoami:
    restart: "no"
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.ranii.pro"

  nginx:
     image: nginx:stable-alpine
     container_name: LEMP_nginx
     restart: always
     volumes:
      - ./code:/code   # Donde metemos el codigo 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuracion del NGINX
     depends_on:
      - php
     labels:
      - "traefik.frontend.rule=Host:dev.ranii.pro"
    
  mariaDB:
      image: mariadb:latest
      container_name: LEMP_mariaDB
      restart: always
      volumes:
       - ./database:/var/lib/mysql:rw
      ports:
       - "3306:3306"  # Aqui si mantenemos el puerto porque no queremos filtrarlo
      labels:
       - "traefik.enable=false" 
      depends_on:
       - nginx
      environment:
       - MYSQL_ROOT_PASSWORD=pass # Password root          
   
  php:
      image: php:7-fpm-alpine
      container_name: LEMP_php
      restart: always
      volumes:
       - ./code:/code
      labels:
       - "traefik.enable=false"
      ports:
       - "9000:9000" # Aqui tampoco quitamos el puerto, se usa en la conf del nginx       

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: LEMP_phpMyAdmin
      restart: always
      labels:
       - "traefik.frontend.rule=Host:db.ranii.pro"
      environment:        
       PMA_ARBITRARY: 1
      depends_on:
       - mariaDB

  tomcat:
      restart: "no"
      image: bitnami/tomcat:latest
      environment:
         - TOMCAT_USERNAME=root
         - TOMCAT_PASSWORD=password
      labels:
       - "traefik.frontend.rule=Host:tomcat.ranii.pro"
      volumes:
       - ./tomcat:/bitnami/tomcat
      depends_on:
       - mariaDB
  samba:
      image: charlesmknox/samba:latest
      restart: always
      container_name: samba
      ports: 
       - 137:137/tcp
       - 137:137/udp
       - 138:138/tcp
       - 138:138/udp
       - 139:139
       - 445:445
       - 445:445/udp
      volumes:
       - /mnt/NAS/descargas:/share/descargas
       - /mnt/NAS/Documentos:/share/Documentos
      labels:
       - "traefik.enable=false"
      command: -u "rani:1706" -s "descargas:/share/descargas:rw:rani" -s "documentos:/share/Documentos:rw:rani"

  teamspeak:
      container_name: teamspeak3
      image: teamspeak
      restart: always
      ports:
       - "9987:9987/udp"
       - "30033:30033"
       - "10011:10011"
       - "41144:41144"
      volumes:
       - /opt/teamspeak/ts3:/data
       - /opt/teamspeak/licensekey.dat:/var/ts3server/licensekey.dat
      environment:
       - TS3SERVER_LICENSE=accept
       - TS3SERVER_DB_PLUGIN=ts3db_mariadb
       - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
       - TS3SERVER_DB_HOST=mariaDB
       - TS3SERVER_DB_USER=root
       - TS3SERVER_DB_PASSWORD=pass
       - TS3SERVER_DB_NAME=teamspeak
       - TS3SERVER_DB_WAITUNTILREADY=30
      depends_on:
       - mariaDB
      labels:
       - "traefik.enable=false"
